### ISSUE TITLE
cl_playerspraydisable | Issue with Improved FPS Booster

### ISSUE THREAD

**Issue by Ford3l** [Inj3-GT/Improved-Fps-Booster-Github-Version#2]
[Improved FPS Booster] ConCommand is blocked! (cl_playerspraydisable)
  1. ConCommand - lua/includes/extensions/player.lua:71
   2. IprFpsBooster_Enable - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:153
    3. DoClick - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:638
     4. unknown - lua/vgui/dlabel.lua:237

[Improved FPS Booster] ConCommand is blocked! (cl_playerspraydisable)
  1. ConCommand - lua/includes/extensions/player.lua:71
   2. IprFpsBooster_Enable - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:142
    3. DoClick - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:641
     4. unknown - lua/vgui/dlabel.lua:237

**the addon swears at this variable cl_playerspraydisable, can you fix pls. all that is above is when the variable is 0. all that is below is when the variable is 1**

[Improved FPS Booster] ConCommand is blocked! (cl_playerspraydisable)
    1. ConCommand - lua/includes/extensions/player.lua:71
        2. IprFpsBooster_Enable - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:153
            3. DoClick - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:443
                4. unknown - lua/vgui/dlabel.lua:237

[Improved FPS Booster] ConCommand is blocked! (cl_playerspraydisable)
    1. ConCommand - lua/includes/extensions/player.lua:71
        2. IprFpsBooster_Enable - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:142
            3. DoClick - lua/improved_fps_booster/improved_fps_booster_client/improved_fps_booster_vgui_control.lua:446
                4. unknown - lua/vgui/dlabel.lua:237

**Comment by Inj3-GT** [comment]
Hello, I'm going to update in a few hours.

Thank you for your report,
